service: mes-driver-service

provider:
  name: aws
  runtime: nodejs16.x
  stage: ${opt:stage, 'dev'}

package:
  individually: true

functions:
  getPhotograph:
    handler: src/functions/getPhotograph/framework/handler.handler
    events:
      - http:
          path: 'driver/photograph/{drivingLicenceNumber?}'
          method: get
custom:
  stages:
    - dev
  webpack:
    webpackConfig: 'webpack-sls-offline.config.js'

plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-offline
