service: mes-driver-service

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'dev'}

package:
  individually: true

functions:
  getDriverPhotograph:
    handler: src/functions/getDriverPhotograph/framework/handler.handler
    events:
      - http:
          path: 'driver/photograph/{drivingLicenceNumber?}'
          method: get
  getDriverSignature:
    handler: src/functions/getDriverSignature/framework/handler.handler
    events:
      - http:
          path: 'driver/signature/{drivingLicenceNumber?}'
          method: get
  postStandardDriver:
    handler: src/functions/postStandardDriver/framework/handler.handler
    events:
      - http:
          path: 'driver/standard'
          method: post
custom:
  stages:
    - dev
  webpack:
    webpackConfig: 'webpack-sls-offline.config.js'

plugins:
  - serverless-dotenv-plugin
  - serverless-webpack
  - serverless-offline
