name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - develop

permissions:
  id-token: write
  contents: write

jobs:
  runs-deploy:
    uses: dvsa/des-workflow-actions/.github/workflows/deploy-backend.yaml@main
    with:
      component: 'api'
    secrets: inherit
