name: Deploy

on:
  workflow_dispatch:
    inputs:
      env:
        description: The environment to deploy to
        type: choice
        default: dev
        options:
          - dev
          - mattb
          - andys
  push:
    branches:
      - develop

permissions:
  id-token: write
  contents: write

jobs:
  runs-deploy:
    uses: dvsa/des-workflow-actions/.github/workflows/deploy-backend.yaml@add-env-input-arg
    secrets: inherit
    with:
      component: 'api'
      env: ${{ inputs.env || 'dev' }}
