name: Deploy

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  runs-deploy:
    uses: dvsa/des-workflow-actions/.github/workflows/deploy-backend.yaml@main
    secrets:
      DES_ACCESS_TOKEN: ${{ secrets.DES_ACCESS_TOKEN }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
