name: Create PR list report

on: pull_request

jobs:
  create-pr-list:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: 🔔 Microsoft Teams Notification
        uses: skitionek/notify-microsoft-teams@v1.0.4
        env:
          GH_TOKEN: ${{ github.token }}
        with:
          webhook_url: ${{ secrets.MSTEAMS_WEBHOOK }}
          raw: >-
            gh pr list --repo dvsa/mes-user-service --json number,title,author --jq '.[] | select(.author.login | contains("snyk") or contains("dependabot"))'
